// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hngXStageTwo.DbContexts;

#nullable disable

namespace hngXStageTwo.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20230911010814_UpdateBirthDate")]
    partial class UpdateBirthDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("hngXStageTwo.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<long>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Anytown, CA",
                            Birthdate = new DateTime(1985, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new DateTime(2023, 9, 11, 2, 8, 14, 76, DateTimeKind.Local).AddTicks(8190),
                            Email = "john.doe@yahoo.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = 2345586752L,
                            UpdatedTime = new DateTime(2023, 9, 11, 2, 8, 14, 76, DateTimeKind.Local).AddTicks(8210)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
